/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSemanalRouteImport } from './routes/_authenticated/semanal'
import { Route as AuthenticatedSemanaIdealRouteImport } from './routes/_authenticated/semana-ideal'
import { Route as AuthenticatedSemanaRouteImport } from './routes/_authenticated/semana'
import { Route as AuthenticatedRevisaoRouteImport } from './routes/_authenticated/revisao'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMensalRouteImport } from './routes/_authenticated/mensal'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedDiariaRouteImport } from './routes/_authenticated/diaria'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAncorasRouteImport } from './routes/_authenticated/ancoras'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSemanalRoute = AuthenticatedSemanalRouteImport.update({
  id: '/semanal',
  path: '/semanal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSemanaIdealRoute =
  AuthenticatedSemanaIdealRouteImport.update({
    id: '/semana-ideal',
    path: '/semana-ideal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSemanaRoute = AuthenticatedSemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisaoRoute = AuthenticatedRevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensalRoute = AuthenticatedMensalRouteImport.update({
  id: '/mensal',
  path: '/mensal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiariaRoute = AuthenticatedDiariaRouteImport.update({
  id: '/diaria',
  path: '/diaria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAncorasRoute = AuthenticatedAncorasRouteImport.update({
  id: '/ancoras',
  path: '/ancoras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ancoras': typeof AuthenticatedAncorasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/diaria': typeof AuthenticatedDiariaRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/mensal': typeof AuthenticatedMensalRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/semana': typeof AuthenticatedSemanaRoute
  '/semana-ideal': typeof AuthenticatedSemanaIdealRoute
  '/semanal': typeof AuthenticatedSemanalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ancoras': typeof AuthenticatedAncorasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/diaria': typeof AuthenticatedDiariaRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/mensal': typeof AuthenticatedMensalRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/semana': typeof AuthenticatedSemanaRoute
  '/semana-ideal': typeof AuthenticatedSemanaIdealRoute
  '/semanal': typeof AuthenticatedSemanalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ancoras': typeof AuthenticatedAncorasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/diaria': typeof AuthenticatedDiariaRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/mensal': typeof AuthenticatedMensalRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/revisao': typeof AuthenticatedRevisaoRoute
  '/_authenticated/semana': typeof AuthenticatedSemanaRoute
  '/_authenticated/semana-ideal': typeof AuthenticatedSemanaIdealRoute
  '/_authenticated/semanal': typeof AuthenticatedSemanalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ancoras'
    | '/configuracoes'
    | '/diaria'
    | '/habitos'
    | '/hoje'
    | '/mensal'
    | '/onboarding'
    | '/revisao'
    | '/semana'
    | '/semana-ideal'
    | '/semanal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ancoras'
    | '/configuracoes'
    | '/diaria'
    | '/habitos'
    | '/hoje'
    | '/mensal'
    | '/onboarding'
    | '/revisao'
    | '/semana'
    | '/semana-ideal'
    | '/semanal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ancoras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/diaria'
    | '/_authenticated/habitos'
    | '/_authenticated/hoje'
    | '/_authenticated/mensal'
    | '/_authenticated/onboarding'
    | '/_authenticated/revisao'
    | '/_authenticated/semana'
    | '/_authenticated/semana-ideal'
    | '/_authenticated/semanal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/semanal': {
      id: '/_authenticated/semanal'
      path: '/semanal'
      fullPath: '/semanal'
      preLoaderRoute: typeof AuthenticatedSemanalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/semana-ideal': {
      id: '/_authenticated/semana-ideal'
      path: '/semana-ideal'
      fullPath: '/semana-ideal'
      preLoaderRoute: typeof AuthenticatedSemanaIdealRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/semana': {
      id: '/_authenticated/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof AuthenticatedSemanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisao': {
      id: '/_authenticated/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof AuthenticatedRevisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensal': {
      id: '/_authenticated/mensal'
      path: '/mensal'
      fullPath: '/mensal'
      preLoaderRoute: typeof AuthenticatedMensalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diaria': {
      id: '/_authenticated/diaria'
      path: '/diaria'
      fullPath: '/diaria'
      preLoaderRoute: typeof AuthenticatedDiariaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ancoras': {
      id: '/_authenticated/ancoras'
      path: '/ancoras'
      fullPath: '/ancoras'
      preLoaderRoute: typeof AuthenticatedAncorasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAncorasRoute: typeof AuthenticatedAncorasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDiariaRoute: typeof AuthenticatedDiariaRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedMensalRoute: typeof AuthenticatedMensalRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRevisaoRoute: typeof AuthenticatedRevisaoRoute
  AuthenticatedSemanaRoute: typeof AuthenticatedSemanaRoute
  AuthenticatedSemanaIdealRoute: typeof AuthenticatedSemanaIdealRoute
  AuthenticatedSemanalRoute: typeof AuthenticatedSemanalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAncorasRoute: AuthenticatedAncorasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDiariaRoute: AuthenticatedDiariaRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedMensalRoute: AuthenticatedMensalRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRevisaoRoute: AuthenticatedRevisaoRoute,
  AuthenticatedSemanaRoute: AuthenticatedSemanaRoute,
  AuthenticatedSemanaIdealRoute: AuthenticatedSemanaIdealRoute,
  AuthenticatedSemanalRoute: AuthenticatedSemanalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
