/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSemanaRouteImport } from './routes/_authenticated/semana'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMensalRouteImport } from './routes/_authenticated/mensal'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAncorasRouteImport } from './routes/_authenticated/ancoras'
import { Route as OauthAgendaReturnRouteImport } from './routes/oauth/agenda/return'
import { Route as OauthAgendaInicioRouteImport } from './routes/oauth/agenda/inicio'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSemanaRoute = AuthenticatedSemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensalRoute = AuthenticatedMensalRouteImport.update({
  id: '/mensal',
  path: '/mensal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAncorasRoute = AuthenticatedAncorasRouteImport.update({
  id: '/ancoras',
  path: '/ancoras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OauthAgendaReturnRoute = OauthAgendaReturnRouteImport.update({
  id: '/oauth/agenda/return',
  path: '/oauth/agenda/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAgendaInicioRoute = OauthAgendaInicioRouteImport.update({
  id: '/oauth/agenda/inicio',
  path: '/oauth/agenda/inicio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ancoras': typeof AuthenticatedAncorasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/mensal': typeof AuthenticatedMensalRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/semana': typeof AuthenticatedSemanaRoute
  '/oauth/agenda/inicio': typeof OauthAgendaInicioRoute
  '/oauth/agenda/return': typeof OauthAgendaReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ancoras': typeof AuthenticatedAncorasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/mensal': typeof AuthenticatedMensalRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/semana': typeof AuthenticatedSemanaRoute
  '/oauth/agenda/inicio': typeof OauthAgendaInicioRoute
  '/oauth/agenda/return': typeof OauthAgendaReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ancoras': typeof AuthenticatedAncorasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/mensal': typeof AuthenticatedMensalRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/semana': typeof AuthenticatedSemanaRoute
  '/oauth/agenda/inicio': typeof OauthAgendaInicioRoute
  '/oauth/agenda/return': typeof OauthAgendaReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ancoras'
    | '/configuracoes'
    | '/habitos'
    | '/hoje'
    | '/mensal'
    | '/onboarding'
    | '/semana'
    | '/oauth/agenda/inicio'
    | '/oauth/agenda/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ancoras'
    | '/configuracoes'
    | '/habitos'
    | '/hoje'
    | '/mensal'
    | '/onboarding'
    | '/semana'
    | '/oauth/agenda/inicio'
    | '/oauth/agenda/return'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ancoras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/habitos'
    | '/_authenticated/hoje'
    | '/_authenticated/mensal'
    | '/_authenticated/onboarding'
    | '/_authenticated/semana'
    | '/oauth/agenda/inicio'
    | '/oauth/agenda/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OauthAgendaInicioRoute: typeof OauthAgendaInicioRoute
  OauthAgendaReturnRoute: typeof OauthAgendaReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/semana': {
      id: '/_authenticated/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof AuthenticatedSemanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensal': {
      id: '/_authenticated/mensal'
      path: '/mensal'
      fullPath: '/mensal'
      preLoaderRoute: typeof AuthenticatedMensalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ancoras': {
      id: '/_authenticated/ancoras'
      path: '/ancoras'
      fullPath: '/ancoras'
      preLoaderRoute: typeof AuthenticatedAncorasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/agenda/return': {
      id: '/oauth/agenda/return'
      path: '/oauth/agenda/return'
      fullPath: '/oauth/agenda/return'
      preLoaderRoute: typeof OauthAgendaReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/agenda/inicio': {
      id: '/oauth/agenda/inicio'
      path: '/oauth/agenda/inicio'
      fullPath: '/oauth/agenda/inicio'
      preLoaderRoute: typeof OauthAgendaInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAncorasRoute: typeof AuthenticatedAncorasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedMensalRoute: typeof AuthenticatedMensalRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSemanaRoute: typeof AuthenticatedSemanaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAncorasRoute: AuthenticatedAncorasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedMensalRoute: AuthenticatedMensalRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSemanaRoute: AuthenticatedSemanaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OauthAgendaInicioRoute: OauthAgendaInicioRoute,
  OauthAgendaReturnRoute: OauthAgendaReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
