ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS breakfast_time time NOT NULL DEFAULT '07:00',
  ADD COLUMN IF NOT EXISTS lunch_time time NOT NULL DEFAULT '12:00',
  ADD COLUMN IF NOT EXISTS snack_time time NOT NULL DEFAULT '15:30',
  ADD COLUMN IF NOT EXISTS dinner_time time NOT NULL DEFAULT '19:00';